# Use the new Docker builds
sudo: false
language: android
android:
  components:
  - platform-tools
  - extra
  - android-23
  - build-tools-25.0.2
jdk:
  - oraclejdk8

script:
  - gradle clean build --stracktrace
