# Use the new Docker builds
sudo: false
language: android
android:
  components:
  - platform-tools
  - extra
  - android-23
  - build-tools-25.0.0
jdk:
  - oraclejdk8

script:
  - ./gradlew clean build --stracktrace

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
